language: python

python:
  - "3.5"

cache: pip

install:
    - pip install -r python_client/requirements.txt
    - pip install -r upload/requirements.txt

script:
  - (cd test;python3 -m pytest)

services:
    - postgresql

before_install:
    - ./generate.sh

before_script:
    - psql -c 'create database backbone_service;' -U postgres
    - psql -U postgres -c "create extension postgis" backbone_service
    - export DB_USER="postgres"
    - psql -c "\i database/backbone_service.psql;" -U ${DB_USER} backbone_service
    - psql -c 'ALTER DATABASE backbone_service SET search_path=public, backbone_service, contrib;' -U postgres
    - psql -c "SELECT postgis_full_version();" -U ${DB_USER} backbone_service
    - psql -c "\d" -U ${DB_USER} backbone_service
    - (cd server;./run.sh build)
    - export BBDEBUG=1
    - (cd server;./run.sh &)
    - sleep 5
    - export PYTHONPATH=$(pwd)/python_client

addons:
    postgresql: "9.6"
    apt:
      packages:
        - postgresql-9.6-postgis-2.3
