definitions:
  Attr:
    type: object
    properties:
      attr_type:
        type: string
      attr_value:
        type: string
      attr_source:
        type: string
      study_name:
        type: string
  Studies:
    type: object
    properties:
      studies:
        type: array
        items:
          $ref: '#/definitions/Study'
      count:
        type: integer
        description: Used when pagination is applied to return the number of results
  Study:
    type: object
    required:
        - code
    properties:
      code:
        type: string
      name:
        type: string
      partner_species:
          type: array
          items:
            $ref: './original_sample.yaml#/definitions/PartnerSpecies'
      locations:
          $ref: './location.yaml#/definitions/Locations'
